package answers;
/**
 * Return the letter that was added to t.
 * 
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * @author Jackson Splinter
 */
public class Problem_0389 
{
    /**
     * Returns the letter that was added to string t.
     * <p>
     * Takes advantage of just searching for one char. Adds all the chars in sting t and then subtracts
     * all the chars in string s. The resulting value is the extra character.
     * <p>
     * O(2n)
     * 
     * @param s base string
     * @param t modified string
     * @return  the letter that was added to t
     */
    public static char findTheDifference(String s, String t) 
    {
        char ans = 0;
        for(int i=0;i<t.length();i++)
        {
            ans = (char) (ans+t.charAt(i));
        }
        for(int i=0;i<s.length();i++)
        {
            ans = (char) (ans-s.charAt(i));
        }
        return ans;
    }
}